
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://marcuseisele.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-16887959-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

author: "Marcus Eisele"
lang: "en"
title: "Marcus Eisele - Developer"

description: "Blog and website of Marcus Eisele."
keywords: "Eisele, Marcus, Entwickler, Developer, Applications, Web"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"
background-img: "https://raw.githubusercontent.com/eiselems/eiselems.github.io/9ef5686dd747efebd7284f5c4317c43b80896aec/assets/background.jpg"


##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "My personal and professional website."
#  - text: "Where’s your will to be weird?"

me-img: "https://cloud.githubusercontent.com/assets/5188694/11317854/92136234-903d-11e5-9ab5-20a3d59c72b4.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "marcuseisele"


syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/career/tss.jpg"
    date: "2016 - heute"
    description: "Working Student: Java Developer"
  - image: "/img/career/daimler.jpg"
    date: "2014 - 2016"
    description: "Working Student: (Web) Application Developer"
  - image: "/img/career/uniStuttgart.jpg"
    date: "2013 - heute"
    description: "M. Sc. Software Engineering"
  - image: "/img/career/uniStuttgart.jpg"
    date: "2010 - 2013"
    description: "B. Sc. Software Engineering"
  - image: "/img/career/aeb_250.jpg"
    date: "October 2007 - September 2009"
    description: "JavaEE Application Developer"
  - image: "/img/career/adv.jpg"
    date: "October 2006 - September 2009"
    description: "ADV Böblingen: <br>Ausbildung 'staatl. geprüfter Informatiker'"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "marcus.eisele@gmail.com"

##################
# Social Buttons #
##################


social:
  - title: "facebook"
    url: "https://www.facebook.com/marcus.eisele"
  - title: "twitter"
    url: "https://twitter.com/eiselems"
  - title: "github"
    url: "https://github.com/eiselems"
  - title: "xing"
    url: "https://www.xing.com/profile/Marcus_Eisele6"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
